#!/bin/sh
RUN=$(dmenu_path | dmenu "$@")
if echo $RUN | ${SHELL:-"/bin/sh"}; then
	echo EI
else
	[ -z $(~/projects/suckless/dmenu/isFirefoxOnWorkspace) ] && firefox-developer-edition --private-window & sleep 0.3
	firefox-developer-edition --private-window "https://duckduckgo.com/?t=ffab&q=$RUN"
fi
